language: python

dist: bionic

python: "3.6"

install:
  - pip install sphinx sphinx-rtd-theme
script:
  - make -C docs clean html
  - touch docs/build/html/.nojekyll # create this file to prevent Github's Jekyll processing
deploy:
  provider: pages
  fqdn: docs.emissions-api.org
  verbose: true
  keep_history: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build/html
  on:
    branch: master
    repo: emissions-api/emissions-api
