language: python

dist: bionic

virtualenv:
  system_site_packages: true

python: "3.6"

jobs:
  include:
    - stage: quick tests
      env: name=flake8
      install:
        - pip install flake8
      script:
        - flake8 emissionsapi

    - stage: quick tests
      env: name=documentation
      language: node_js
      node_js: 11
      install:
        - npm install -g markdownlint-cli
      script:
        - markdownlint .

    - stage: deployment
      env: name=gh-pages
      addons:
        apt:
          packages:
            - python3-gdal
            - python3-pycurl
            - python3-psycopg2
      install:
        - pip install sphinx sphinx-rtd-theme
        - pip install -r requirements.txt
      script:
        - make -C docs clean html
        - touch docs/build/html/.nojekyll # create this file to prevent Github's Jekyll processing
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs/build/html
      on:
        branch: master
        repo: emissions-api/emissions-api
