version: '2'
services:
  db:
    container_name: emissionsapi-postgres
    image: docker.io/mdillon/postgis
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db
