version: 2
jobs:
  flake8:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: install flake8
          command: pip install flake8
      - run:
          name: test with flake8
          command: flake8 emissionsapi
  install buster:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: install base dependencies
          command: |
            apt update
            apt install -y build-essential libcurl4-gnutls-dev libgnutls28-dev \
                libpq-dev python3 python3-venv python3-dev
      - run:
          name: install as module
          command: |
            python3 -m venv /tmp/module-env
            /tmp/module-env/bin/python setup.py install
            cd /
            . /tmp/module-env/bin/activate
            python -c "import emissionsapi"
            python -c "import emissionsapi.download"
            python -c "import emissionsapi.db"
            python -c "import emissionsapi.preprocess"
            deactivate
            rm -r /tmp/module-env
      - run:
          name: complete installation
          command: |
              python3 -m venv /tmp/env
              cp .testdata/emissionsapi.yml .
              . /tmp/env/bin/activate
              pip install -r requirements.txt
              python -c "import emissionsapi"
              python -c "import emissionsapi.web"
              python -c "import emissionsapi.download"
              python -c "import emissionsapi.db"
              python -c "import emissionsapi.preprocess"
              deactivate
              rm -r /tmp/env
  preprocess:
    docker:
      - image: debian:buster
      - image: circleci/postgres:11-postgis
        environment:
          POSTGRES_USER: emissionsapi
          POSTGRES_PASSWORD: emissionsapi
          POSTGRES_DB: emissionsapi
    steps:
      - checkout
      - run:
          name: install emissionsapi
          command: |
              apt update
              apt install -y build-essential libcurl4-gnutls-dev libgnutls28-dev \
                  libpq-dev python3 python3-venv python3-dev
              python3 -m venv env
              ./env/bin/pip install -r requirements.txt
              cp .testdata/emissionsapi.yml .
      - run:
          name: Waiting for Postgres to be ready
          command: |
              for i in `seq 1 10`;
              do
                  python3 -c "import socket; import sys; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect_ex(('localhost', 5432)) and sys.exit(1)" && echo Success && exit 0
                  echo -n .
                  sleep 1
              done
              echo Failed waiting for Postgres && exit 1
      - run:
          name: preprocess test data
          command: ./env/bin/python -m emissionsapi.preprocess
workflows:
  version: 2
  simple tests:
    jobs:
      - flake8
      - install buster
  integration tests:
    jobs:
      - preprocess
