name: Build and deploy Docs

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install
        # temporary fix since sphinx-rtd-theme fails with the latest sphinx
        # https://github.com/readthedocs/sphinx_rtd_theme/issues/1343
        run: pip install sphinx!=5.2.0.post0 sphinx-rtd-theme
      - name: Build
        run: |
            make -C docs clean html
            touch docs/build/html/.nojekyll
            echo docs.emissions-api.org > docs/build/html/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true
